### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by avdb13** [innocentvoice/EAGLS-Extractor#1]
![maxresdefault](https://user-images.githubusercontent.com/60188643/176521026-a3bef51b-4ba9-40f0-a987-9f855fb2435a.jpg)

**Comment by innocentvoice** [comment]
too lazy :p i will push the source code later

**Comment by avdb13** [comment]
> on mean time your can use the release to download the tool

I'm not using any piece of software that I can't audit the source code of.

**Comment by innocentvoice** [comment]
> > on mean time your can use the release to download the tool
> 
> I'm not using any piece of software that I can't audit the source code of.

then simply don't use it?
